apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
    spec:
      containers:
        - name: backend-node
          image: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 80