apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-zumbacafew
  name: backend-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
    spec:
      containers:
        - name: backend-node
          image: alpha03/node-backend:latest-arm64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080