apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
    spec:
      containers:
        - name: backend-node
          image: 677518839775.dkr.ecr.us-west-2.amazonaws.com/zumbacafew:backend_259b3a2deef7e8b1bfa0d574a996acbfbc63a13a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080