apiVersion: v1
kind: Service
metadata:
  namespace: app-zumbacafew
  name: backend-node
spec:
  selector:
    app: backend-node
  ports:
  - port: 8080
    targetPort: 8080
    name: backend-node
  clusterIP: None