apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mongo
  labels:
    app: db-mango
spec:
  selector:
    matchLabels:
      app: db-mango
  replicas: 1
  template:
    metadata:
      labels:
        app: db-mango
    spec:
      containers:
        - name: db-mango
          image: alpha03/mongo-database
          imagePullPolicy: Always
          command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
          ports:
            - containerPort: 27017