apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-vue
  template:
    metadata:
      labels:
        app: frontend-vue
    spec:
      containers:
        - name: frontend-vue
          image: 677518839775.dkr.ecr.us-west-2.amazonaws.com/zumbacafew:frontend_259b3a2deef7e8b1bfa0d574a996acbfbc63a13a
          imagePullPolicy: Always
          ports:
            - containerPort: 80