apiVersion: v1
kind: Service
metadata:
  namespace: app-zumbacafew
  name: frontend-vue
spec:
  type: LoadBalancer
  selector:
    app: frontend-vue
  ports:
  - port: 80
    targetPort: 80
    name: frontend-vue
