apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-deployment.yaml
- db-service.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml

images:
- name: backend
  newName: 396229223364.dkr.ecr.us-west-2.amazonaws.com/zumbacafew
  newTag: backend_c1cdc2c698a98862685b9a9c8cbd1ed0ea9be87a
- name: database
  newName: 396229223364.dkr.ecr.us-west-2.amazonaws.com/zumbacafew
  newTag: database_c1cdc2c698a98862685b9a9c8cbd1ed0ea9be87a
- name: frontend
  newName: 396229223364.dkr.ecr.us-west-2.amazonaws.com/zumbacafew
  newTag: frontend_c1cdc2c698a98862685b9a9c8cbd1ed0ea9be87a
