apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-deployment.yaml
- db-service.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml

images:
- name: backend
  newName: 677518839775.dkr.ecr.us-west-2.amazonaws.com/zumbacafew
  newTag: backend_4389994b8de7463499a379d115a99553164d5286
- name: database
  newName: 677518839775.dkr.ecr.us-west-2.amazonaws.com/zumbacafew
  newTag: database_4389994b8de7463499a379d115a99553164d5286
- name: frontend
  newName: 677518839775.dkr.ecr.us-west-2.amazonaws.com/zumbacafew
  newTag: frontend_4389994b8de7463499a379d115a99553164d5286
