version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
    ports: 
      - "8080:8080"
    volumes:
      - ../server:/workspace:cached
    working_dir: /workspace
    command: sh -c "npm install && nodemon start"
    depends_on: 
      - db
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports: 
      - "27017:27017"
    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here
volumes:
  mongodb-data: